spring:
  profiles:
    active:
      on-profiles: aws
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://onepostershop.cviarmgnkzbn.ap-northeast-2.rds.amazonaws.com:3306/onepostershop
    username: admin
    password: xorhs123

  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

file:
  dir: /home/ubuntu/image/
